import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "..");
const assetDir = path.join(repoRoot, "assets");
const repoEnvPath = path.join(path.resolve(repoRoot, "../.."), ".env");
const companionEnvPath = "/Users/chrisdonahue/Code/companion/.env.local";

const baseStyle =
  "Premium editorial 16:9 technical illustration for a developer workshop. Modern software engineering aesthetic, light background, charcoal ink, teal and blue accents, small amber and green highlights, crisp vector-like detail, spacious professional composition, no readable text, no letters, no words, no numbers, no logos, no brand marks.";

const prompts = [
  {
    name: "hero-agent-harnesses.png",
    prompt: `${baseStyle} Show a modern IDE workspace inside a protective but lightweight harness: rails, boundaries, test indicators, review shields, and a human engineer guiding an abstract AI assistant. The mood should feel controlled, useful, and calm, not locked down or scary.`,
  },
  {
    name: "prompt-to-harness.png",
    prompt: `${baseStyle} Show a single prompt card on the left helping one agent session, contrasted with a durable repo harness on the right containing instructions, playbooks, scripts, test checks, and review shields that support many future sessions.`,
  },
  {
    name: "rules-moves-tools-checks.png",
    prompt: `${baseStyle} Show a clean four-part operating system around an AI coding assistant: rules as instruction cards, moves as reusable playbook paths, tools as safe command/tool adapters, checks as tests and review shields. Use four distinct zones connected in a loop.`,
  },
  {
    name: "copilot-instructions-operating-manual.png",
    prompt: `${baseStyle} Show a repository operating manual being inserted into a software repo: instruction cards, generated-file lock, safe command terminal, risky path boundary, and done checklist icons guiding an abstract coding assistant.`,
  },
  {
    name: "blast-radius-boundaries.png",
    prompt: `${baseStyle} Show agent permissions as expanding blast-radius rings around a repo: read files, edit local code, run allowlisted commands, and ship/release actions behind a human approval gate. Make boundaries look enabling and precise.`,
  },
  {
    name: "skills-playbooks.png",
    prompt: `${baseStyle} Show reusable agent skills as blank playbook cards or procedure modules being selected before and after code generation. Include a human engineer choosing the right move for the task. Every card, panel, button, and window must be blank or use only tiny abstract line texture; absolutely no labels, no readable text, no faux words, no UI text.`,
  },
  {
    name: "team-habits.png",
    prompt: `${baseStyle} Show team engineering habits becoming reusable agent procedures: bug triage evidence, migration dry-run safety, UI screen inspection, and PR review evidence, all represented as connected workflow stations around a repo.`,
  },
  {
    name: "runnable-scripts.png",
    prompt: `${baseStyle} Show safe repository scripts as clearly marked command lanes an AI agent can run: changed tests, verification bundle, local smoke check, and PR evidence collector. The commands should be visual terminal blocks with abstract lines only.`,
  },
  {
    name: "soft-checks.png",
    prompt: `${baseStyle} Show soft lint and quality checks producing warnings rather than hard stop signs: issue markers, caution flags, accessibility hints, type-safety signals, and a clean report flowing back to an AI assistant for cleanup.`,
  },
  {
    name: "post-generation-review.png",
    prompt: `${baseStyle} Show code generated by an AI assistant moving through a post-generation review harness: changed tests, soft lint report, diagnostic scan, and final evidence summary before a human reviewer inspects the diff.`,
  },
  {
    name: "harness-learning-loop.png",
    prompt: `${baseStyle} Show a learning loop from AI failure to cause analysis to harness improvement to a better next session. Include instruction update, new script, added test, and review checklist as visual repair actions.`,
  },
  {
    name: "inspectable-work.png",
    prompt: `${baseStyle} Show AI-generated work becoming inspectable: bounded work area, visible tool path, passing checks, review shield, and a human engineer calmly reviewing evidence before merge.`,
  },
];

function parseArgs(argv) {
  const args = { only: null };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--only") {
      const next = argv[index + 1];
      if (!next) throw new Error("--only requires an asset filename.");
      args.only = next;
      index += 1;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

async function readEnvKeyFrom(filePath) {
  let envText = "";
  try {
    envText = await fs.readFile(filePath, "utf8");
  } catch {
    return "";
  }
  for (const line of envText.split(/\r?\n/)) {
    const match = line.match(/^\s*XAI_API_KEY\s*=\s*(.*)\s*$/);
    if (!match) continue;
    let value = match[1].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    return value.trim();
  }
  return "";
}

async function readXaiApiKey() {
  const envKey = process.env.XAI_API_KEY?.trim();
  if (envKey) return envKey;
  return (await readEnvKeyFrom(repoEnvPath)) || (await readEnvKeyFrom(companionEnvPath));
}

function fallbackSvg(title, accent) {
  return Buffer.from(`
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900">
  <rect width="1600" height="900" fill="#f6f8fb"/>
  <rect x="160" y="140" width="1280" height="620" rx="32" fill="#ffffff" stroke="#d8e0ea" stroke-width="3"/>
  <rect x="240" y="228" width="360" height="420" rx="18" fill="#111827"/>
  <rect x="690" y="228" width="670" height="84" rx="18" fill="#ffffff" stroke="#d8e0ea" stroke-width="3"/>
  <rect x="690" y="354" width="670" height="84" rx="18" fill="#ffffff" stroke="#d8e0ea" stroke-width="3"/>
  <rect x="690" y="480" width="670" height="84" rx="18" fill="#ffffff" stroke="#d8e0ea" stroke-width="3"/>
  <rect x="690" y="606" width="670" height="84" rx="18" fill="#ffffff" stroke="#d8e0ea" stroke-width="3"/>
  <path d="M600 438 C680 438 650 270 690 270" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round"/>
  <path d="M600 438 C680 438 650 396 690 396" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round" opacity=".75"/>
  <path d="M600 438 C680 438 650 522 690 522" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round" opacity=".55"/>
  <path d="M600 438 C680 438 650 648 690 648" fill="none" stroke="${accent}" stroke-width="8" stroke-linecap="round" opacity=".4"/>
  ${Array.from({ length: 12 }, (_, i) => `<rect x="292" y="${280 + i * 28}" width="${180 + (i % 4) * 38}" height="9" rx="4" fill="${i % 3 === 0 ? accent : "#64748b"}" opacity="${i % 3 === 0 ? ".9" : ".55"}"/>`).join("")}
  <text x="800" y="820" text-anchor="middle" font-family="Aptos, Arial" font-size="34" fill="#334155">${title}</text>
</svg>`);
}

async function generateOne(item, index, apiKey) {
  const out = path.join(assetDir, item.name);
  if (!apiKey) {
    await fs.writeFile(out, fallbackSvg(item.name.replace(".png", ""), index % 2 ? "#f59e0b" : "#0e9f9a"));
    return { name: item.name, status: "fallback-no-key" };
  }

  const response = await fetch("https://api.x.ai/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({
      model: "grok-imagine-image-quality",
      prompt: item.prompt,
      aspect_ratio: "16:9",
      resolution: "1k",
      response_format: "b64_json",
    }),
  });
  const text = await response.text();
  if (!response.ok) {
    await fs.writeFile(out, fallbackSvg(item.name.replace(".png", ""), index % 2 ? "#f59e0b" : "#0e9f9a"));
    return { name: item.name, status: "fallback-http", detail: response.status };
  }
  const data = JSON.parse(text);
  const b64 = data?.data?.[0]?.b64_json;
  if (!b64) {
    await fs.writeFile(out, fallbackSvg(item.name.replace(".png", ""), index % 2 ? "#f59e0b" : "#0e9f9a"));
    return { name: item.name, status: "fallback-empty" };
  }
  await fs.writeFile(out, Buffer.from(b64, "base64"));
  return { name: item.name, status: "grok" };
}

async function readExistingManifest() {
  try {
    const existing = JSON.parse(await fs.readFile(path.join(assetDir, "asset-manifest.json"), "utf8"));
    return Array.isArray(existing) ? existing : [];
  } catch {
    return [];
  }
}

await fs.mkdir(assetDir, { recursive: true });
const args = parseArgs(process.argv.slice(2));
const selectedPrompts = args.only ? prompts.filter((item) => item.name === args.only) : prompts;
if (args.only && selectedPrompts.length === 0) throw new Error(`No prompt configured for ${args.only}.`);
const apiKey = await readXaiApiKey();
const results = [];
for (let index = 0; index < selectedPrompts.length; index++) {
  const promptIndex = prompts.findIndex((item) => item.name === selectedPrompts[index].name);
  results.push(await generateOne(selectedPrompts[index], promptIndex, apiKey));
}
const manifest = args.only
  ? [
      ...((await readExistingManifest()).filter((item) => !results.some((result) => result.name === item.name))),
      ...results,
    ]
  : results;
await fs.writeFile(path.join(assetDir, "asset-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(JSON.stringify(results, null, 2));
